### ISSUE TITLE
Remove DrawText

### ISSUE THREAD

**Issue by outsider31000** [VORPCORE/VORP-Inventory#82]
Draw text needs to be removed on drop items. it cost too much to the resource. as it's not optimized at all.
Instead, make the name of the item or weapon be shown on the prompt that already exists.

server empty with items dropped 
![Screenshot 2022-04-07 171602](https://user-images.githubusercontent.com/87246847/162249754-d6755bdf-b4c5-4304-84ee-85a2ab3d78b1.jpg)

server empty with no items dropped 

![Screenshot 2022-04-07 171700](https://user-images.githubusercontent.com/87246847/162249943-2acaed81-5926-41cf-9d5b-5a6bc31f95c0.jpg)

**Comment by t3chman** [comment]
It's probably the loop to check if a player is in range of the dropped item to then _display_ the label via DrawText, not necessarily DrawText itself. This needs further investigation to identify the root cause of the latency. However, I would start with assessing the conditional/loop logic and optimizing that first if possible.

**Comment by SimpleSandman** [comment]
Given this is a `Tick` without any sleeps, delays, or pauses in the loop, this would generate constant work on the CPU. I can add an `await Delay(100);` (or 100 millisecond pause) and test if that fixes the issue.

**Comment by t3chman** [comment]
I was curious and looked through https://github.com/VORPCORE/VORP-Inventory/blob/66365770278b491466570c084a551516c7ffb920/VORP-Inventory/vorpinventory-cl/Pickups.cs

It's really inefficient. For one, it's running on a Tick, meaning looping at a maximum rate on the client. If there are no pickups (dropped items), then it returns and doesn't run any further logic, but if there is even a single item, it is running many natives and a lot of logic that is really not necessary and shouldn't even be handled client side either. We certainly need to optimize this.

I'll look into patching it at least temporarily until it can be completely re-worked. Ideally a dropped item would trigger an event that notifies the server which would keep a list of items and every value needed for later logic so that natives don't need to be run so frequently and repetitively. Then the server can notify all clients with a group of newly dropped items at a set interval (say every few seconds at most) and a new player/client can retrieve a full list of dropped items as well. Then the DrawText really should only be displayed at close to a maximum reasonable framerate (120fps or every 8ms roughly).

**Comment by t3chman** [comment]
> Given this is a `Tick` without any sleeps, delays, or pauses in the loop, this would generate constant work on the CPU. I can add an `await Delay(100);` (or 100 millisecond pause) and test if that fixes the performance issue.

Yes, this may temporarily alleviate the issue to a degree, but I will say that Delay's are used all too frequently in VORP. There is a lot of hang time in much of the logic that is due to this.

**Comment by SimpleSandman** [comment]
It sounds like you have a better handle on how this could be optimized. If you want, I'll leave this one to you while I work on something else.

**Comment by t3chman** [comment]
Yeah not a problem. This isn't a critical issue and I don't mind addressing it when I have some time :) Might work on that in a bit

**Comment by SimpleSandman** [comment]
Perfect! I also didn't think about the "flashing" DrawText every 100ms until you said something.

**Comment by outsider31000** [comment]
Drawtext should not be displayed at all. 
It's bad. 
The reason its there its to tell what the item is. 
Which it can be done through the prompt  that already exists  there is no reason why a drawtext should be displayed when there's no need for it. 

This will be close now as it's to be handle  in discord.
